return {
  'airblade/vim-gitgutter',
  'scrooloose/syntastic',
  'scrooloose/nerdtree',
  'sheerun/vim-polyglot',
  'bling/vim-airline',
  'tpope/vim-rails',
  'tpope/vim-bundler',
  'thoughtbot/vim-rspec',
  'tpope/vim-endwise',
  'tpope/vim-surround',
  'ervandew/supertab',
  'jiangmiao/auto-pairs',
  'othree/yajs.vim',
  'tpope/vim-eunuch',
  'gcmt/wildfire.vim',
  'janko/vim-test',
  'kassio/neoterm',
  'scrooloose/nerdcommenter',
  'Xuyuanp/nerdtree-git-plugin',
  'terryma/vim-multiple-cursors',
  'tpope/vim-projectionist',
  'tpope/vim-fugitive',
  {'junegunn/fzf', dir = '~/.fzf', build = './install --all' },
  'junegunn/fzf.vim',
  'mhartington/oceanic-next'
}
